server:
  port: 8082

spring:
  application:
    name: stage-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info

# =========================
# FILE STORAGE CONFIG
# =========================
app:
  upload:
    dir: ${APP_UPLOAD_DIR:/app/uploads/stage}

# =========================
# FEIGN CONFIG
# =========================
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8081}