apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gestion-projet

resources:
  - secret.yaml
  - configmap.yaml
  - uploads-pv-pvc.yaml
  - stage-deployment.yaml

images:
  - name: nour292/stage-service
    newTag: "113"
