apiVersion: v1
kind: Secret
metadata:
  name: stage-secrets
  namespace: gestion-projet
type: Opaque
stringData:
  STAGE_DB_URL: "jdbc:postgresql://ep-shiny-darkness-anvk72ua-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require"
  STAGE_DB_USERNAME: "neondb_owner"
  STAGE_DB_PASSWORD: "npg_E1aJvPHsWDB2"
  JWT_SECRET: "MySuperSecretKeyForJwtTokenGeneration2026!!!"